[[ISSUERS]]
address = "rhuMHXnxGhGqJiHDBbwCqFb5KMAaGkwJeK"
name = "Blinx Digital Technologies"

[[TOKENS]]
issuer = "rhuMHXnxGhGqJiHDBbwCqFb5KMAaGkwJeK"
currency = "XDT"
name = "BlinxDT"
desc = "Blinx Digital Technologies is a cloud-enabled blockchain payment system prioritizing innovation, interoperability, and efficiency in the financial sector. By combining cloud-like infrastructure with a secure blockchain foundation and adhering to ISO 20022 standards, we facilitate secure institutional university and healthcare transfers under a unified payment network across institutional dining & merchant services, instilling confidence in financial transactions.
"
icon = "https://github.com/XDT-Blinx-Digital-Technologies/xdt/blob/main/IMG_6456.jpeg"

[[TOKENS.WEBLINKS]]
url = "https://xdtxrp.org"
type = "Blinx Digital Technologies"
title = "XDT (Blinx Digital Technologies)"

